---
name: CAD-Format-STL
version: v0.0.1
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: read/write 3D stereolithography files
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CAD-Format-STL
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://scratchcomputing.com/svn/CAD-Format-STL/trunk
requires:
  Class::Accessor::Classy: v0.1.3
build_requires:
  Module::Build: 0.26
  Test::More: 0
provides:
  CAD::Format::STL:
    file: lib/CAD/Format/STL.pm
    version: v0.0.1
  CAD::Format::STL::part:
    file: lib/CAD/Format/STL/part.pm
    version: v0.0.1
generated_by: Module::Build version 0.3001
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
